apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: comp-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: comp-test
    app.kubernetes.io/part-of: rsenvapp
  name: comp-test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: comp-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: comp-test
    spec:
      containers:
      - image: quay.io/abarbaro-org/spi-demos-gvzk-tenant/rsenvapp/comp-test@sha256:348eda95c0810945b5cd63820e79c19235a015c89394d2ac9bdceba61fc57019
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
